    IF 
    SAYA TIDAK AKAN TERLAMBAT LAGI KARENA TIDAK HUJAN DI SAMATA
    
    ELSE
    KALAU SAYA TERLAMBAT, YAH SAYA TETAP MASUK.

    ELSE IF 
    SAYA MINTA IZIN

    ELSE IF
    MENDING PULANG
    
